### ISSUE TITLE
[BUG] Linux: Opening a explorer does not work when the directories contain special characters

### ISSUE THREAD

**Issue by useredsa** [soramimi/Guitar#100]
Hello,

I can't open the explorer in a path that contains special characters such as spaces or accented vowels. The standard error output shows that the encoding follows the typical url encoding:

`/home/useredsa/repo%202` instead of `/home/useredsa/repo 2`.

Thank you in advance,

**Comment by useredsa** [comment]
> `/home/useredsa/repo%202` instead of `/home/useredsa/repo 2`.

Fixed small typo in the description of the error. The idea is to show that `<space>` is written as `%20`.

**Comment by soramimi** [comment]
fixed
