### ISSUE TITLE
Don't use `COLORTERM` to detect the terminal.

### ISSUE THREAD

**Issue by useredsa** [soramimi/Guitar#101]
I have not seen an specification although I searched where does this variable come from. However, I have seen that in [`vscode`], [`kitty`] and  [`alacritty`] that the contents of this variable is not the terminal emulator, but `truecolor` to show that the terminal supports truecolor.

Therefore, in [guitar's terminal call], it tries to run the program `truecolor` that does not exist.

More references: https://gist.github.com/XVilka/8346728#detection

I suggest just checking the `TERM` variable or directly invoking `x-terminal-emulator`.

[`vscode`]: https://github.com/microsoft/vscode/issues/76352
[`kitty`]: https://github.com/kovidgoyal/kitty/blob/8b4427a4e2e8d3207b405a6418cfaac4a114373c/kitty/child.py#L217
[`alacritty`]: https://github.com/alacritty/alacritty/blob/7aafbb757d485c5ff065324464dde8b5322cdd92/alacritty_terminal/src/tty/mod.rs#L74

[guitar's terminal call]: https://github.com/soramimi/Guitar/blob/32acf843a73208cdf6ba6505fedfb0181f4fb59e/src/Terminal.cpp#L50

**Comment by useredsa** [comment]
Actually, the `TERM` variable is not valid either because in some terminals it is not the name of the terminal emulator program (like in kitty, where it is set to `xterm-kitty`).

Whatever is used, it's probably wise to check whether that command is available and otherwise fall back to `x-terminal-emulator`.

**Comment by mrspirytus** [comment]
I also did try to click on Terminal button and noting happened. Ubuntu Mate 20.04 x64
But free seconds later application did quit on me and this is what I got (I started Guitar from Terminal)

```
Opening in existing browser session.
/bin/sh: 1: truecolor: not found
/bin/sh: 1: truecolor: not found
QMetaObject::connectSlotsByName: No matching signal for on_pushButton_browse_default_working_dir_clicked()
QLayout: Attempting to add QLayout "" to SettingBehaviorForm "page_behavior", which already has a layout
QLayout: Attempting to add QLayout "" to SettingProgramsForm "page_programs", which already has a layout
QLayout: Attempting to add QLayout "" to SettingNetworkForm "page_network", which already has a layout
QLayout: Attempting to add QLayout "" to SettingExampleForm "page_example", which already has a layout

```

**Comment by soramimi** [comment]
Now you can choose terminal emulator program you like.

![image](https://user-images.githubusercontent.com/3043124/114252732-c06d1e00-99e1-11eb-8cc0-3f00f7fcd37a.png)
