### ISSUE TITLE
"Reset" not working

### ISSUE THREAD

**Issue by Gillissie** [soramimi/Guitar#117]
I had one txt file with changes that I wanted to reset before pulling. Every time I do I reset, the file disppears from the changed files list for a split second, then returns with the same changes again. As a workaround, I had to stash the changes, pull, then drop the stash.

**Comment by geovens** [comment]
I noticed that when there are space(s) in the file path, reset does not work for that single file. Probably could be fixed by adding quotation marks ("") in the command.
