### ISSUE TITLE
[Cache Issue] Gravatar Request Spamming

### ISSUE THREAD

**Issue by OdinVex** [soramimi/Guitar#121]
Any **additional** attempts at fetching Gravatars or Libravatars for the **same address** should be ignored and should all return the result from the first request. That way, you don't have 50+ requests for the same user until it is looked up.

Example: Loading up a repository with a bunch of new users will spam Gravatar for requests, even **for the same user**, until they're all resolved.

**Comment by soramimi** [comment]
Sorry for leaving this issue unresolved for so long. But I've completely reimplemented the AvatarLoader class, so I don't think this issue will arise anymore, so I'm closing this issue.
