### ISSUE TITLE
Is it possible to support building with Qt4?

### ISSUE THREAD

**Issue by barracuda156** [soramimi/Guitar#127]
We have no Qt5+ on Mac PowerPC :)

**Comment by soramimi** [comment]
Sorry. Qt4 is not supported. Now supports Qt5 and Qt6. Also, I cannot test the app on Mac PowerPC.

**Comment by barracuda156** [comment]
> Sorry. Qt4 is not supported. Now supports Qt5 and Qt6. Also, I cannot test the app on Mac PowerPC.

Don’t worry about PowerPC, there are no arch-specific issues with Qt4, AFAIK. If it can work on i386, it will work on PPC.

Did you have an earlier branch or version with Qt4 support? (Of course I do not know how involving it is to fix it for the current versions. I won’t expect any upstream developer to spend significant time on such a task.)
