### ISSUE TITLE
webclient error

### ISSUE THREAD

**Issue by vnl** [soramimi/Guitar#13]
Hello, 
Using Qt Createor 4.2.1 Community with the Kit being Qt 5.8.0 MSVC2015 64 bit. 
Getting the following error as shown in the image. 

![image](https://user-images.githubusercontent.com/1355466/27088675-3c3b5306-5050-11e7-86b3-79153ffb6c63.png)

**Comment by soramimi** [comment]
Please add the following line.

> #include <openssl/x509.h>

If it works well, it will be fixed at the next commit.

**Comment by vnl** [comment]
Sorry tried it but did not work. Same error. 
Added #include <openssl/x509.h> in line 36

**Comment by vnl** [comment]
Also, would it be possible to include libeay and ssleay along with the lib files? Reason is, I installed the latest version of openSSL only that the files are completely renamed now with the newer versions.
![image](https://user-images.githubusercontent.com/1355466/27091474-200aa53a-5058-11e7-8230-29915f5f4437.png)

**Comment by soramimi** [comment]
Please wait for a few days. I have never built a 64-bit version. I will try to make a 64-bit development environment next weekend. 

If you can, please try to build a 32-bit version.

By the way, where did you get OpenSSL? Did you build it yourself?

**Comment by yumetodo** [comment]
>By the way, where did you get OpenSSL? Did you build it yourself?

may be from here.
https://slproweb.com/products/Win32OpenSSL.html

**Comment by vnl** [comment]
OpenSSL link is as provided by @yumetodo 

Unfortunately I did not download the 32 bit Qt. I do not mind waiting, I will give it a shot too.

Thank you for getting back to me. 

A wish list perhaps (just a wish list and I can help you out too)
1. Qt 5.9.0 
2. VS2017 build

**Comment by yumetodo** [comment]
@vnl

When `OPENSSL_NO_SHA` macro is defined, all sha-1 related feature will be disabled.
SHA-1 is **very dangerous algorithm** because of hash collision.

https://bugreports.qt.io/browse/QTBUG-51553

openssl 1.0.2l https://github.com/openssl/openssl/blob/b69ae442a3b3e168d73c53dcd04bacf33eee8569/crypto/include/internal/x509_int.h

```cpp
struct x509_st {
    X509_CINF *cert_info;
    X509_ALGOR *sig_alg;
    ASN1_BIT_STRING *signature;
    int valid;
    int references;
    char *name;
    CRYPTO_EX_DATA ex_data;
    /* These contain copies of various extension values */
    long ex_pathlen;
    long ex_pcpathlen;
    unsigned long ex_flags;
    unsigned long ex_kusage;
    unsigned long ex_xkusage;
    unsigned long ex_nscert;
    ASN1_OCTET_STRING *skid;
    AUTHORITY_KEYID *akid;
    X509_POLICY_CACHE *policy_cache;
    STACK_OF(DIST_POINT) *crldp;
    STACK_OF(GENERAL_NAME) *altname;
    NAME_CONSTRAINTS *nc;
# ifndef OPENSSL_NO_RFC3779
    STACK_OF(IPAddressFamily) *rfc3779_addr;
    struct ASIdentifiers_st *rfc3779_asid;
# endif
# ifndef OPENSSL_NO_SHA
    unsigned char sha1_hash[SHA_DIGEST_LENGTH];
# endif
    X509_CERT_AUX *aux;
} /* X509 */ ;
```

**Comment by soramimi** [comment]
These code make a fingerprint string, but not used (it used for debug only). Therefore, I think it is okay to comment out that code.

example:

```
	if (x509) {
#if 0
		std::string fingerprint;
		for (int i = 0; i < SHA_DIGEST_LENGTH; i++) {
			if (i > 0) {
				fingerprint += ':';
			}
			char tmp[10];
			sprintf(tmp, "%02X", x509->sha1_hash[i]);
			fingerprint += tmp;
		}
		fingerprint += '\n';
		output_debug_string(fingerprint.c_str());
#endif
```

**Comment by vnl** [comment]
Is it updated to x64 yet?

**Comment by soramimi** [comment]
Committed the fix right now. please check it.

**Comment by soramimi** [comment]
...and, I have not used OpenSSL v1.1.0
Please use v1.0.x instead of v1.1.0
The required DLLs are libeay32.dll and ssleay32.dll

**Comment by vnl** [comment]
Will do, need to pull the latest. I will also update once this is done.

**Comment by vnl** [comment]
This can be closed. Compiled and running in VS2017. 
Steps:
1. Install openssl 1.0.x
2. Open Guiatr.pro file in VS2017
3. Open zlib.pro file in VS2017 (same solution as above)
4. Modify the project file to change the paths of openssl and zlib project.
