### ISSUE TITLE
error: Plugin Metadata file "darkstyleplugin.json" does not exist.

### ISSUE THREAD

**Issue by GermanAizek** [soramimi/Guitar#140]
@soramimi, how to build latest commit on Linux? I using docs BUILDING.md and build using CMake, here bad result output:

Commit: https://github.com/soramimi/Guitar/commit/67080a423a5ede7f75ab323f9b2cc0ef9113b01a

```
AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/src/darktheme/DarkStylePlugin.h"
into
  "SRC:/build/src/guitar-lib_autogen/CVNSVTCKEY/moc_DarkStylePlugin.cpp"
Process failed with return value 1

Output
------
Guitar/src/darktheme/DarkStylePlugin.h:12:1: error: Plugin Metadata file "darkstyleplugin.json" does not exist. Declaration will be ignored

make[2]: *** [src/CMakeFiles/guitar-lib_autogen.dir/build.make:75: src/guitar-lib_autogen/timestamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:241: src/CMakeFiles/guitar-lib_autogen.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

**Comment by soramimi** [comment]
I'm sorry. That build document is old and I haven't used cmake recently, so it may not work. Please try qmake.

**Comment by GermanAizek** [comment]
> I'm sorry. That build document is old and I haven't used cmake recently, so it may not work. Please try qmake.

@soramimi, building using qmake by instruction invalid.

```
debian@debian:~/GIT/Guitar/build$ qmake ..
Cannot read /home/debian/GIT/Guitar: file to open is a directory
Error processing project file: ..
```

But if you specify exact name project file, he will defined and starts Makefile configuration

```
debian@debian:~/GIT/Guitar/build$ qmake ../Guitar.pro 
Info: creating stash file /home/debian/GIT/Guitar/build/.qmake.stash
WARNING: Failure to find: filetype/file/src/magic.h
WARNING: Failure to find: filetype/file/src/magic.h
WARNING: Failure to find: filetype/file/src/patchlevel.h
WARNING: Failure to find: filetype/misc/unistd.h
```

Perhaps this is due to new Qt6 because I have newest packages in Debian 12 Unstable (Testing). Update the instructions for Linux, don't be lazy.
