### ISSUE TITLE
Some buttons are set as 'Cacnel' in the english transtation

### ISSUE THREAD

**Issue by miniwark** [soramimi/Guitar#154]
Small typo i the English translation of Guitar 1.2.999
In some cases the button is labeled as 'Cacnel' instead of 'Cancel'

I have see it in:
- Edit .gitignore
- Edit .git/config
- Edit .global .gitonfig

(also the 'Cancel' button is sometime a 'Close' button but this is probably ok)

**Comment by soramimi** [comment]
fix (af401f8)
