### ISSUE TITLE
Add an installation tutorial

### ISSUE THREAD

**Issue by BarbzYHOOL** [soramimi/Guitar#16]
How to install it?

**Comment by yumetodo** [comment]
@BarbzYHOOL You should check below:
https://soramimi.github.io/Guitar/

**Comment by BarbzYHOOL** [comment]
There is no installation for linux

**Comment by soramimi** [comment]
Which OS do you use?
Do you need executable binary? or build it yourself?

**Comment by BarbzYHOOL** [comment]
Ubuntu 14.04

There should be an easy install tool :)

**Comment by soramimi** [comment]
Tell me the result of `uname -a`

**Comment by manucsek** [comment]
Hi, if you want to build Guitar from source, here's an English guide: https://soramimi.github.io/Guitar/build-en.html (it wasn't me who wrote this)
I followed this guide on Debian with no problem.

**Comment by BarbzYHOOL** [comment]
Hmm it uses Ruby etc, I don't want to install these things, so I'll close the issue, sorry
