### ISSUE TITLE
open current directory from terminal

### ISSUE THREAD

**Issue by souhaiebtar** [soramimi/Guitar#30]
i tried to open current directory from terminal but it didn't work, is there a way to do it ?

**Comment by soramimi** [comment]
please tell me your environment. (OS etc..)
what command did you type on your terminal ?

**Comment by souhaiebtar** [comment]
i'm using ubuntu 16.04 and i open the binary file Guitar /usr/apps/Guitar/Guitar, Guitar open just fine but i didn't show my current repo,
the command used is
```
/usr/apps/Guitar/Guitar .
```

**Comment by soramimi** [comment]
you try 
/usr/apps/Guitar/Guitar --open-here
and refer
https://github.com/soramimi/Guitar/blob/master/git-gui

**Comment by souhaiebtar** [comment]
thanks, it work with the command you mentioned
