### ISSUE TITLE
Linux: Guitar stops reading git command output after a while

### ISSUE THREAD

**Issue by gbl** [soramimi/Guitar#35]
Thanks a lot for this great software, it has become my favourite Git gui.

However, there's a problem when I'm using the software on Linux; after some time, especially when switching repositories. When this happens, and your're running from the command line, you'll see `failed: pipe` messages on the terminal.

I think this is because, when starting a subprocess to execute a git command, the stdout from the subcommand gets closed, but the stderr doesn't. Because of this, the file descriptor pool fills up, and if you do a `ls /proc/<pid-of-Guitar>/fd`, you see lots of files that point to pipes.

Closing `fd_err_write` at the end of the loop in UnixProcess.cpp::run() fixes this:

```
diff --git a/src/unix/UnixProcess.cpp b/src/unix/UnixProcess.cpp
index 930e122..334eac0 100644
--- a/src/unix/UnixProcess.cpp
+++ b/src/unix/UnixProcess.cpp
@@ -190,6 +190,7 @@ protected:
                        t2.wait();
 
                        close(fd_out_write);
+                       close(fd_err_write);
 
                } catch (std::string const &e) {
                        close(stdin_pipe[R]);

```

If you want me to, I can make this a pull request, but I'm reluctant to start a fork for such a small thing.

**Comment by soramimi** [comment]
now merged your patch.
thanks!
