### ISSUE TITLE
Highlight word diff

### ISSUE THREAD

**Issue by ghost** [soramimi/Guitar#76]
Is it possible to add "word diffing" highlight?

![pic.1](https://i.imgur.com/0yByTOY.jpg)

**Comment by soramimi** [comment]
I would love to make it happen. But that would be a big change.

**Comment by Symbian9** [comment]
Could you take a look on `kdiff3` sources?

- http://kdiff3.sourceforge.net/

I use its Qt-only version (*kdiff3-qt* package) and it has expected "word diff highlighting", which colors could be configured:

![pic.1](https://i.imgur.com/XF3YPZX.png)

![pic.2](https://i.imgur.com/KURNtII.png)

**Comment by KarlZeilhofer** [comment]
Meld has this feature too. 
https://meldmerge.org/
Perhaps a temporary workaround could be, to launch an external diff tool. 

Currently I'm still with GitKraken, but Gitar is very promising. There is an option "open in external diff tool":  
![2020-07-12_003](https://user-images.githubusercontent.com/2773445/87235696-ea57cc80-c3de-11ea-8c17-b2e9cd80d89b.png)

**Comment by asmwarrior** [comment]
Hi, there is a similar project named [gitahead](https://github.com/gitahead/gitahead), which is QT based and implemented in C++.

I just see that it compares some added or remove lines, see the code below:

https://github.com/gitahead/gitahead/blob/bb747caef098140d9674990b1d79d096d1eac8df/src/ui/DiffView.cpp#L1323-L1371

It looks like it just split a line to different words(tokens), and then compare token by token.

**Comment by soramimi** [comment]
now available character-diffing
![image](https://user-images.githubusercontent.com/3043124/184499085-3db21d90-c295-486c-bd95-361eb9151a27.png)

**Comment by asmwarrior** [comment]
> now available character-diffing ![image](https://user-images.githubusercontent.com/3043124/184499085-3db21d90-c295-486c-bd95-361eb9151a27.png)

good news.

Any way, I can try a nightly build?

**Comment by Symbian9** [comment]
> Any way, I can try a nightly build?

@asmwarrior, Check out nightly builds here:

- https://files.soramimi.jp/guitar/nightly/

**Comment by asmwarrior** [comment]
> > Any way, I can try a nightly build?
> 
> @asmwarrior, Check out nightly builds here:
> 
>     * https://files.soramimi.jp/guitar/nightly/

Thanks, it nightly build works OK!

I think one remaining feature is that I would like to see the "selective stage" feature like the "Git GUI", for example, I can stage a single line or single hunk. Currently, I can't only stage a single file.

Thanks.
