### ISSUE TITLE
Setup failed on ubuntu 20.04 lts

### ISSUE THREAD

**Issue by gregorieb** [soramimi/Guitar#77]
Hi,

I have been using guitar on Ubuntu 18.04.4, and it worked just fine. Today I tried to install it on Ubuntu 20.04 from the same .deb and it did not work. Did some research and the problem seems to be libssl, 1.0.0 is not shipped with 20.04, version 1.1 is. On the ssl web page it says v 1.0.0 is not supported anymore. 
-----------------------------
https://www.openssl.org/source/
Note: The latest stable version is the 1.1.1 series. This is also our Long Term Support (LTS) version, supported until 11th September 2023. All other versions (including 1.1.0, 1.0.2, 1.0.0 and 0.9.8) are now out of support and should not be used. Users of these older versions are encourage to upgrade to 1.1.1 as soon as possible.
------------------------------

Solution seems to be to install old 1.0.0 libssl. is there any other workaround? any plans to update guitar to use 1.1.1? any suggestions?

------------------------------------------------------------

This is the full output from the commands I ran.

dpkg -i guitar_1.1.1_amd64.deb

dpkg: dependency problems prevent configuration of guitar:
 guitar depends on libssl1.0.0; however:
  Package libssl1.0.0 is not installed.

After that I ran apt update & upgrade and got this:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 guitar : : libssl1.0.0 but it is not installable
E: Unmet dependencies. Try '' with no packages (or specify a solution).

then ran apt --fix-broken install

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  guitar
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 304060 files and directories currently installed.)
Removing guitar (1.1.1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...

**Comment by soramimi** [comment]
Guitar 1.1 depends on OpenSSL 1.0. However, with Ubuntu 19 and later, OpenSSL 1.0 is gone and OpenSSL 1.1 is provided instead. I have completed work on this change and will be available in the next version of Guitar. If you want to use it right now, try Nightly Build.

**Comment by gregorieb** [comment]
Great news, any way to stay informed about the new release date?

**Comment by scottstensland** [comment]
@gregorieb as with any github repo to get notice of changes hit the Watch button on the repo and pick the flavor of notification

**Comment by gregorieb** [comment]
Many thanks!!!! will be watching.... for now using nightly build.
