### ISSUE TITLE
Cannot be installed on Ubuntu 20.04

### ISSUE THREAD

**Issue by tomasnorre** [soramimi/Guitar#80]
guitar : Depends: libssl1.0.0 but it is not installable

On ubuntu 20.04 the libssl1.1 is available but not the libssl.1.0.0 version. I don't know what the changes are between the two libssl versions, but would expect it to be updateable as it's minor release. If they do semantic versioning.

**Comment by tomasnorre** [comment]
Looks like  you have already tried. 
https://github.com/soramimi/Guitar/blob/c501b9e823b9c87c334750f8b69dd8c5e9a1a9b2/docs/build_guide-en/build_guide_for_linux-en.md#01-dependencies

**Comment by soramimi** [comment]
See the issue #77, Please try Nightly Build.

**Comment by tomasnorre** [comment]
Thanks that worked, I only searched in open issues for libssl, my bad.

**Comment by tomasnorre** [comment]
I can install but crashes directly after the setup wizard.
