### ISSUE TITLE
Need some way to hide really long labels so that it doesn't block commit messages

### ISSUE THREAD

**Issue by tommai78101** [soramimi/Guitar#81]
In my workplace, we require our git branches have descriptive names, so we can keep track of which branch has features and bugfixes. However, it becomes a problem for Guitar.

This is what I'm seeing right now:

![image](https://user-images.githubusercontent.com/6444116/82229311-467b0480-98f8-11ea-99f9-9ba2a4c5eba7.png)

As you can see, the labels of the local branch and remote tracking branch takes up the entire message column, thus blocking the git commit messages.

There should be a way to either do one of the following in order to read the git commit message behind the labels:

* Hide the labels on mouse hover.
* Hide the labels on selecting the commit item.
* Add some transparency value to all of the labels. (+ settings configuration for transparency in the preferences menu)

Would like to see this issue be resolved someday in Guitar. Thanks.

**Comment by soramimi** [comment]
I've just implemented it. Press Ctrl+L toggle between show/hide.
Please try the latest master branch or the nightly build from tomorrow.
If the commit message is too long, select the commit and look at the tooltip or status bar.

**Comment by tommai78101** [comment]
Oh cool! Thank you so much. I'll close the issue once I verify that it works. Or you can close it, if you want to. :D

**Comment by tommai78101** [comment]
Verified it works. Sorry that it took so long to respond back.
