### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by jesus2099** [soramimi/Guitar#82]
Could you add Guitar to [Debian package list](https://packages.debian.org/search?suite=buster&section=all&arch=any&searchon=names&keywords=guitar), somehow?
This way I could install via Synaptic (I have Debian Xfce, if it ever matters).
Otherwise, I still don't know how to install and uninstall stuff or know what is installed on my PC.
I am new to Linux so sorry if my question is inappropriate.

**Comment by soramimi** [comment]
I don't know how to register with the official Debian packages, and I don't have the confidence to maintain it, so I'm looking for contributors. For now, you can download the Nightly Build and install it with the `apt` command.

https://files.soramimi.jp/guitar/nightly/

`sudo apt install ./guitar_1.1.999_amd64.deb
`

**Comment by jesus2099** [comment]
I will learn how `apt` works. It's useful anyway.
Thank you for your answer, @soramimi. 😉
