### ISSUE TITLE
"Author" column doesn't automatically adjust its width for user avatars

### ISSUE THREAD

**Issue by kobligo** [soramimi/Guitar#88]
Gravatar icons and names in the "Author" column overlap.
This makes them both very hard to read, and the column width needs to be adjusted manually every time that Guitar is launched to get a good view at everything.

The column should take the avatar image into consideration and be displayed at an increased width when there's a contributer with an avatar involved in a project and avatars are enabled.

**Comment by soramimi** [comment]
I don't think the author's column is important. It is shown for reference. The icon does not reserve the area to display it, and intentionally draws it semi-transparently. If you want to see the details, you can either manually expand it or double-click it to open the properties dialog.
